### ISSUE TITLE
Database Research

### ISSUE THREAD

**Issue by denizgungor** [swe-ms-boun/2018fall-swe574-g2#13]
Relational/NonRelational DB will be discussed. Preparations will be done.

**Comment by mehmetkayaalp** [comment]
I think we can use a relational or nonrelational database (no matter). Actually, story data will be unstructured so that's why the nonrelational database is more appropriate for this project to store user story information. However, when we think about the limited duration of this project, we can also use a relational database that we all are more familiar.

**Comment by yasserkabbout** [comment]
As per our discussion with you and Umut over Slack, we agreed on using PostgreSQL as our database. @mehmetkayaalp @umutseven92
